[package]
name = "ffi_java_scd"
version = "1.2.0"
authors = [ "WeDPR <wedpr@webank.com>" ]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ffi_java_scd"
crate-type = [ "cdylib" ]

[dependencies]
jni = "0.13.0"
protobuf = "2.10.1"
selective_certificate_disclosure = { path = "../../../solution/selective_certificate_disclosure" }
wedpr_crypto = { path = "../../../crypto/" }
wedpr_ffi_common = { path = "../../ffi_common/" }
wedpr_ffi_macros = { path = "../../../ffi/ffi_macros/" }
wedpr_protos = { path = "../../../protos/" }
wedpr_utils = { path = "../../../common/utils" }

[build-dependencies]
cbindgen = "0.9.0"

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.13.1", default-features = false }
