[package]
name = "wedpr_protos"
version = "1.0.0"
authors = ["WeDPR <wedpr@webank.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protobuf = "2.10.1"
protoc-rust = "2.10.1"
