[package]
name = "wedpr_macros"
version = "1.1.0"
authors = [ "WeDPR <wedpr@webank.com>" ]
edition = "2018"
license = "Apache-2.0"
description = "Library of WeDPR shared utilities."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
